"""Clean up database - only keep order_tasks table

Revision ID: 179edb080ba7
Revises: d15b5af0da16
Create Date: 2025-07-31 16:02:55.500257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179edb080ba7'
down_revision: Union[str, Sequence[str], None] = 'd15b5af0da16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
