"""change_order_status_to_integer_values

Revision ID: bae2446b3ee3
Revises: 
Create Date: 2025-07-31 20:04:22.773216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bae2446b3ee3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_release_config_id'), table_name='shop_release_config')
    op.drop_index(op.f('shop_name'), table_name='shop_release_config')
    op.drop_table('shop_release_config')

    # 手动添加：修改 order_status 字段从文字枚举改为数字枚举
    # 首先更新现有数据
    op.execute("UPDATE order_tasks SET order_status = '1' WHERE order_status = '进行中'")
    op.execute("UPDATE order_tasks SET order_status = '2' WHERE order_status = '完成'")
    op.execute("UPDATE order_tasks SET order_status = '3' WHERE order_status = '失败'")

    # 然后修改字段类型
    op.alter_column('order_tasks', 'order_status',
                   existing_type=sa.Enum('进行中', '完成', '失败', name='orderstatus'),
                   type_=sa.Enum('1', '2', '3', name='orderstatus_new'),
                   existing_nullable=True,
                   existing_server_default='进行中')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 手动添加：回滚 order_status 字段从数字枚举改回文字枚举
    op.alter_column('order_tasks', 'order_status',
                   existing_type=sa.Enum('1', '2', '3', name='orderstatus_new'),
                   type_=sa.Enum('进行中', '完成', '失败', name='orderstatus'),
                   existing_nullable=True)

    # 更新数据
    op.execute("UPDATE order_tasks SET order_status = '进行中' WHERE order_status = '1'")
    op.execute("UPDATE order_tasks SET order_status = '完成' WHERE order_status = '2'")
    op.execute("UPDATE order_tasks SET order_status = '失败' WHERE order_status = '3'")

    op.create_table('shop_release_config',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_name', mysql.VARCHAR(length=200), nullable=False, comment='店铺名称（唯一）'),
    sa.Column('release_interval_days', mysql.INTEGER(), autoincrement=False, nullable=False, comment='释放间隔天数（完成订单后多少天可以重新下单）'),
    sa.Column('timezone', mysql.VARCHAR(length=50), nullable=False, comment='时区设置'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否启用释放限制（false表示无限制）'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('shop_name'), 'shop_release_config', ['shop_name'], unique=True)
    op.create_index(op.f('ix_shop_release_config_id'), 'shop_release_config', ['id'], unique=False)
    # ### end Alembic commands ###
