"""增加新的字段

Revision ID: c9d3e35b247a
Revises: 179edb080ba7
Create Date: 2025-07-31 16:12:59.342297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d3e35b247a'
down_revision: Union[str, Sequence[str], None] = '179edb080ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_tasks', sa.Column('alipay_trade_no', sa.String(length=100), nullable=True, comment='支付宝交易号'))
    op.add_column('order_tasks', sa.Column('receiver_name', sa.String(length=100), nullable=True, comment='收货人姓名'))
    op.add_column('order_tasks', sa.Column('receiver_address', sa.String(length=500), nullable=True, comment='收货地址'))
    op.add_column('order_tasks', sa.Column('receiver_phone', sa.String(length=20), nullable=True, comment='收货人手机号'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_tasks', 'receiver_phone')
    op.drop_column('order_tasks', 'receiver_address')
    op.drop_column('order_tasks', 'receiver_name')
    op.drop_column('order_tasks', 'alipay_trade_no')
    # ### end Alembic commands ###
