"""Remove unused tables - keep only order_tasks

Revision ID: d15b5af0da16
Revises: 9a9963e9830f
Create Date: 2025-07-31 15:52:49.333154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd15b5af0da16'
down_revision: Union[str, Sequence[str], None] = '9a9963e9830f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 按正确顺序删除表（先删除有外键的表，再删除被引用的表）

    # 1. 删除 purchase_records 表（引用 accounts, shops, products）
    op.drop_table('purchase_records')

    # 2. 删除 purchase_rules 表（引用 accounts, platforms, shops）
    op.drop_table('purchase_rules')

    # 3. 删除 products 表（引用 platforms, shops）
    op.drop_table('products')

    # 4. 删除 shops 表（引用 platforms）
    op.drop_table('shops')

    # 5. 删除 accounts 表（引用 platforms）
    op.drop_table('accounts')

    # 6. 最后删除 platforms 表（被其他表引用）
    op.drop_table('platforms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.VARCHAR(length=100), nullable=False, comment='å•†å“\x81åœ¨å¹³å\x8f°çš„å”¯ä¸€æ\xa0‡è¯†'),
    sa.Column('product_name', mysql.VARCHAR(length=500), nullable=False, comment='å•†å“\x81å\x90\x8dç§°'),
    sa.Column('product_url', mysql.VARCHAR(length=1000), nullable=True, comment='å•†å“\x81é“¾æŽ¥'),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='å•†å“\x81ä»·æ\xa0¼'),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=True, comment='å•†å“\x81åˆ†ç±»'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='çŠ¶æ€\x81ï¼š1-æ\xad£å¸¸ï¼Œ0-ä¸‹æž¶'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name='products_ibfk_1'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name='products_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    comment='å•†å“\x81è¡¨',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='å•†å“\x81è¡¨',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uk_platform_product'), 'products', ['platform_id', 'product_id'], unique=True)
    op.create_table('purchase_rules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('platform_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shop_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rule_type', mysql.ENUM('daily_shop_limit', 'daily_platform_limit', 'daily_account_limit'), nullable=False),
    sa.Column('limit_count', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='é™\x90åˆ¶æ¬¡æ•°'),
    sa.Column('reset_time', mysql.TIME(), server_default=sa.text("'00:00:00'"), nullable=True, comment='é‡\x8dç½®æ—¶é—´ï¼ˆåŸºäºŽè´¦å\x8f·æ—¶åŒºï¼‰'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='çŠ¶æ€\x81ï¼š1-å\x90¯ç”¨ï¼Œ0-ç¦\x81ç”¨'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('purchase_rules_ibfk_1')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('purchase_rules_ibfk_2')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('purchase_rules_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    comment='è´\xadä¹°é™\x90åˆ¶è§„åˆ™è¡¨',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='è´\xadä¹°é™\x90åˆ¶è§„åˆ™è¡¨',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('accounts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_name', mysql.VARCHAR(length=100), nullable=False, comment='è´¦å\x8f·å\x90\x8dç§°/ç”¨æˆ·å\x90\x8d'),
    sa.Column('account_id', mysql.VARCHAR(length=100), nullable=True, comment='å¹³å\x8f°è´¦å\x8f·ID'),
    sa.Column('nickname', mysql.VARCHAR(length=100), nullable=True, comment='è´¦å\x8f·æ˜µç§°'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='çŠ¶æ€\x81ï¼š1-æ\xad£å¸¸ï¼Œ0-ç¦\x81ç”¨'),
    sa.Column('daily_purchase_limit', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='æ¯\x8fæ—¥è´\xadä¹°é™\x90åˆ¶æ¬¡æ•°'),
    sa.Column('timezone', mysql.VARCHAR(length=50), server_default=sa.text("'Asia/Shanghai'"), nullable=True, comment='æ—¶åŒºè®¾ç½®'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name='accounts_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    comment='è´¦å\x8f·è¡¨',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='è´¦å\x8f·è¡¨',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uk_platform_account'), 'accounts', ['platform_id', 'account_name'], unique=True)
    op.create_table('platforms',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False, comment='å¹³å\x8f°å\x90\x8dç§°ï¼Œå¦‚ï¼š1688ã€\x81æ‹¼å¤šå¤šã€\x81æ·˜å®\x9dç\xad‰'),
    sa.Column('code', mysql.VARCHAR(length=20), nullable=False, comment='å¹³å\x8f°ä»£ç\xa0\x81ï¼Œå¦‚ï¼š1688ã€\x81pddã€\x81taobao'),
    sa.Column('base_url', mysql.VARCHAR(length=255), nullable=True, comment='å¹³å\x8f°åŸºç¡€URL'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='çŠ¶æ€\x81ï¼š1-å\x90¯ç”¨ï¼Œ0-ç¦\x81ç”¨'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='ç”µå•†å¹³å\x8f°è¡¨',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='ç”µå•†å¹³å\x8f°è¡¨',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'platforms', ['name'], unique=True)
    op.create_index(op.f('code'), 'platforms', ['code'], unique=True)
    op.create_table('shops',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_id', mysql.VARCHAR(length=100), nullable=False, comment='åº—é“ºåœ¨å¹³å\x8f°çš„å”¯ä¸€æ\xa0‡è¯†'),
    sa.Column('shop_name', mysql.VARCHAR(length=200), nullable=False, comment='åº—é“ºå\x90\x8dç§°'),
    sa.Column('shop_url', mysql.VARCHAR(length=500), nullable=True, comment='åº—é“ºé“¾æŽ¥'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='çŠ¶æ€\x81ï¼š1-æ\xad£å¸¸ï¼Œ0-ç¦\x81ç”¨'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name='shops_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    comment='åº—é“ºè¡¨',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='åº—é“ºè¡¨',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uk_platform_shop'), 'shops', ['platform_id', 'shop_id'], unique=True)
    op.create_table('purchase_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_date', sa.DATE(), nullable=False, comment='è´\xadä¹°æ—¥æœŸï¼ˆåŸºäºŽè´¦å\x8f·æ—¶åŒºï¼‰'),
    sa.Column('purchase_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='è´\xadä¹°æ—¶é—´ï¼ˆUTCï¼‰'),
    sa.Column('order_id', mysql.VARCHAR(length=100), nullable=True, comment='è®¢å\x8d•å\x8f·'),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='è´\xadä¹°é‡‘é¢\x9d'),
    sa.Column('quantity', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='è´\xadä¹°æ•°é‡\x8f'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='çŠ¶æ€\x81ï¼š1-æˆ\x90åŠŸï¼Œ0-å¤±è´¥ï¼Œ2-å\x8f–æ¶ˆ'),
    sa.Column('remark', mysql.TEXT(), nullable=True, comment='å¤‡æ³¨ä¿¡æ\x81¯'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('purchase_records_ibfk_1')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('purchase_records_ibfk_3')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('purchase_records_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    comment='è´\xadä¹°è®°å½•è¡¨',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='è´\xadä¹°è®°å½•è¡¨',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_purchase_time'), 'purchase_records', ['purchase_time'], unique=False)
    op.create_index(op.f('idx_purchase_date'), 'purchase_records', ['purchase_date'], unique=False)
    op.create_index(op.f('idx_account_shop_date'), 'purchase_records', ['account_id', 'shop_id', 'purchase_date'], unique=False)
    # ### end Alembic commands ###
